//
//  FoodItems.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.2
//

import Foundation
import UIKit
import AWSDynamoDB
class FoodItems: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _itemId: String?
    var _itemDescription: String?
    var _originalPrice: NSNumber?
    var _title: String?
    
    class func dynamoDBTableName() -> String {
        return "rizzosfinepizza-mobilehub-25238770-FoodItems"
    }
    
    class func hashKeyAttribute() -> String {
        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {
        return "_itemId"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_userId" : "userId",
               "_itemId" : "itemId",
               "_itemDescription" : "itemDescription",
               "_originalPrice" : "originalPrice",
               "_title" : "title",
        ]
    }
}
